import turtle
import math

## Head
leonardo = turtle.Turtle()
leonardo.speed(0)
leonardo.begin_fill()
leonardo.circle(110)
leonardo.color("green")
leonardo.end_fill()
leonardo.setheading(90)
leonardo.color("green", "black")##!!!!!!!!
leonardo.forward(120)
leonardo.left(90)
leonardo.forward(4)
leonardo.setheading(90)
leonardo.forward(-85)

## mask
leonardo.circle(90,20)
leonardo.setheading(90)
leonardo.forward(30)
leonardo.begin_fill()
leonardo.color("purple")
leonardo.right(90)
leonardo.circle(340,20)
leonardo.circle(330,-40)
leonardo.right(180)
leonardo.circle(80,60)
leonardo.setheading(90)
leonardo.circle(-40, 150)
leonardo.setheading(90)
leonardo.left(-270)
leonardo.circle(-80,70)
leonardo.right(150)
leonardo.circle(150,20)
leonardo.setheading(45)
leonardo.circle(50,20)
leonardo.circle(-70,10)
leonardo.circle(-20,120)
leonardo.setheading(-20)
leonardo.circle(540,10)
leonardo.setheading(8)
leonardo.circle(443,14)
leonardo.setheading(-40)
leonardo.circle(-50, 85)
leonardo.end_fill()

## right eye
leonardo.color("purple")## !!!!
leonardo.setheading(140)
leonardo.forward(30)
leonardo.right(315)
leonardo.forward(90) ## center
leonardo.right(20)
leonardo.forward(25)
leonardo.setheading(90)
leonardo.begin_fill()
leonardo.circle(20)
leonardo.color("white")
leonardo.end_fill()
leonardo.color("black")
leonardo.left(90)
leonardo.forward(30)
leonardo.begin_fill()

leonardo.left(90)
leonardo.color('brown')
leonardo.circle(10)
leonardo.end_fill()

leonardo.left(-90)
leonardo.color("white")
leonardo.forward(-30)


# ## left eye
leonardo.color("purple")
leonardo.right(180)
leonardo.forward(99)
leonardo.setheading(90)
leonardo.begin_fill()
leonardo.circle(19)
leonardo.color("white")
leonardo.end_fill()

leonardo.left(90)
leonardo.forward(30)
leonardo.begin_fill()

leonardo.left(90)
leonardo.color('brown')
leonardo.circle(10)
leonardo.end_fill()
leonardo.color("white")
leonardo.left(90)
leonardo.forward(30)
leonardo.right(180)

## smile
leonardo.color("white")
leonardo.forward(35)
leonardo.color("purple")
leonardo.forward(30)
leonardo.setheading(-90)
leonardo.forward(31)
leonardo.color("green")
leonardo.forward(54)
leonardo.color("brown")
leonardo.left(90)
leonardo.pensize(3)
leonardo.circle(90,20)
leonardo.pensize(2)
leonardo.circle(80,-40)
leonardo.color("green")

## body
leonardo.pensize(0)
leonardo.circle(80,20)
leonardo.setheading(270)
leonardo.color("green")
leonardo.pensize(1)
leonardo.forward(40)
leonardo.right(90)
leonardo.begin_fill()
leonardo.color("black","green")
leonardo.circle(150)
leonardo.end_fill()

## armour
leonardo.setheading(270)
leonardo.color("green")
leonardo.forward(60)
leonardo.right(90)
leonardo.begin_fill()
leonardo.color("black","orange")
leonardo.circle(90)
leonardo.end_fill()
leonardo.setheading(270)
leonardo.color("orange")
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(20)## moving right
leonardo.color("orange")

## right chest
leonardo.begin_fill()
leonardo.color("dark orange")
for i in range(4):
        leonardo.forward(30)
        leonardo.left(90)
leonardo.end_fill()

## left chest
leonardo.setheading(0)
leonardo.color("orange")
leonardo.forward(40)
leonardo.setheading(270)
leonardo.begin_fill()
leonardo.color("dark orange")
for i in range(4):
        leonardo.forward(30)
        leonardo.left(90)
leonardo.end_fill()

## abs
leonardo.right(90)
leonardo.color("orange")
leonardo.forward(20)
leonardo.setheading(270)
leonardo.forward(60)

leonardo.pensize(4)
leonardo.color("dark orange")
leonardo.forward(69)
leonardo.forward(-10)
leonardo.right(90)
leonardo.forward(20)
leonardo.forward(-40)
leonardo.forward(22)
leonardo.setheading(90)
leonardo.forward(20)

leonardo.right(90)
leonardo.forward(24)
leonardo.forward(-48)
leonardo.forward(27)

leonardo.setheading(90)
leonardo.forward(25)
leonardo.right(90)
leonardo.forward(30)
leonardo.forward(-60)

## right arm
leonardo.setheading(120)
leonardo.color("orange")
leonardo.forward(95)
leonardo.color("green")
leonardo.forward(68)
leonardo.left(100)
leonardo.color("green")
leonardo.begin_fill()
leonardo.pensize(1)
leonardo.color("green")
leonardo.forward(120)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(120)
leonardo.left(90)
leonardo.forward(30)
leonardo.end_fill()
## knuckle right
leonardo.begin_fill()
leonardo.left(95)
leonardo.forward(110)
leonardo.right(80)
leonardo.color("dark green")
leonardo.circle(19)
leonardo.end_fill()

## left arm
leonardo.color("green")
leonardo.setheading(45)
leonardo.forward(110)
leonardo.setheading(0)
leonardo.forward(220)
leonardo.begin_fill()
leonardo.right(45)
leonardo.forward(120)
leonardo.right(90)
leonardo.forward(30)
leonardo.right(90)
leonardo.forward(120)
leonardo.right(90)
leonardo.color("green")
leonardo.forward(32)
leonardo.end_fill()

## knucle left
leonardo.seth(305)
leonardo.color("green")
leonardo.forward(110)
leonardo.right(80)
leonardo.begin_fill()
leonardo.color("dark green")
leonardo.circle(19)
leonardo.end_fill()

leonardo.setheading(125)
leonardo.color("green")
leonardo.forward(110)
leonardo.right(80)

leonardo.color("brown")
leonardo.begin_fill()
leonardo.color("brown")
leonardo.pensize(3)
leonardo.forward(160)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(168)
leonardo.left(90)
leonardo.forward(30)
leonardo.end_fill()

## weapon
leonardo.left(90)
leonardo.forward(120)
leonardo.begin_fill()
turtle.colormode(255)
leonardo.color(123, 63, 0)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(60)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(60)
leonardo.end_fill()

## Legs

leonardo.setheading(0)
leonardo.color("white")
leonardo.forward(100)
leonardo.right(90)
leonardo.forward(350)
leonardo.right(90)
leonardo.forward(220)
leonardo.right(90)
leonardo.forward(36)
leonardo.left(90)
leonardo.begin_fill()
leonardo.color("green")

leonardo.forward(140)
leonardo.left(90)
leonardo.forward(60)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(45)
leonardo.forward(60)
leonardo.right(90)
leonardo.forward(60)
leonardo.left(45)
leonardo.forward(30)
leonardo.setheading(90)
leonardo.forward(50)
leonardo.end_fill()

## feets
leonardo.left(170)
leonardo.color("green")
leonardo.forward(40)
leonardo.right(90)
leonardo.begin_fill()
leonardo.color("dark green")
leonardo.circle(17)
leonardo.end_fill()

leonardo.color("green")
leonardo.right(45)
leonardo.forward(90)
leonardo.left(105)
leonardo.forward(100)
leonardo.right(90)
leonardo.begin_fill()
leonardo.color("dark green")
leonardo.circle(17)
leonardo.end_fill()

leonardo.hideturtle()

turtle.mainloop()